
name: Build the website and the pdf output

on:
  push:
    branches:
      - main  # Triggers workflow on push to the main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Quarto
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      # Step 3: Install R dependencies
      - name: Install R packages
        run: |
         Rscript -e 'install.packages(c("tidyverse", "quarto", "tinytex","ModelMetrics"), repos = "https://cloud.r-project.org")'
         Rscript -e 'tinytex::install_tinytex()'

      # Step 4: Set up Python
      #- name: Set up Python
      #  uses: actions/setup-python@v5
      #  with:
      #    python-version: '3.11'  # Change to the desired version

      # Step 5: Install Python dependencies
      #- name: Install Python packages
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install pandas  # Add more packages if needed

      # Step 6: Compile document
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
